### ISSUE TITLE
デバッグに対応できるようにする

### ISSUE THREAD

**Issue by uedatakeshi** [uedatakeshi/panels#2]
electronとして実行した状態だとfirebugも使えないし、cssもどう反映されてるのか分からない。
ローカルのブラウザでも同じように動く環境にしておく必要あり？

**Comment by itagakishintaro** [comment]
同じ悩みに遭遇して、以下をやってみたけどダメでした。
上田さんもやってみてもらえませんか?
https://github.com/atom/electron/blob/master/docs/tutorial/debugging-main-process.md

**Comment by uedatakeshi** [comment]
node-inspector
してから、
ブラウザでこのアドレスを叩くと、
http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
chromeの開発ツールと同じ画面になって、SourcesとConsoleには何か出てますが、他は何も出ないですね。Sourcesも出てるのはJSファイルだけです。
あとConsoleのエラー

Error: Cannot find module '/Users/xxxxx/.npm-packages/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v45-darwin-x64/debug.node'

**Comment by uedatakeshi** [comment]
一応、browserify使って、ブラウザからindex.htmlを開いても同じに画面が出るように変更しました。
（bundle.jsを読み込んでます）
